name: flutter_test_page_object
description: Page object for flutter test. Included extensions for basic actions
version: 0.1.0
repository: https://github.com/AnnaVadimovna/flutter_test_page_object
issue_tracker: https://github.com/AnnaVadimovna/flutter_test_page_object/issues
homepage: https://github.com/AnnaVadimovna/flutter_test_page_object
documentation: https://github.com/AnnaVadimovna/flutter_test_page_object/wiki

environment:
  sdk: ">=2.12.0 <3.0.0"  

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter